### ISSUE TITLE
Possible Bug - IFC model not loading correctly.

### ISSUE THREAD

**Issue by usmanhussainESP** [ThatOpen/engine_web-ifc#967]
### Describe the bug 📝

Hey, 

After loading this particular model (ifc file), I see that not all the items are loaded correctly. Some elements may be missing. I am testing directly with the latest version of the official template.

In the following screenshot you can see the original model loaded correctly using usBIM.
![image (1)](https://github.com/user-attachments/assets/29cbc7cf-5930-4792-85ff-1f51d988537f)
And this is the result of having loaded it using the official template:
![image (2)](https://github.com/user-attachments/assets/533d7e14-477e-4c59-921d-250625c2997d)

As you can see, most of the roof has not been loaded. Some parts are loaded but the geometry is not correct.

![image](https://github.com/user-attachments/assets/980795a9-a551-43dd-b699-1003bc1151c0)

I am aware that you need the IFC file to replicate the problem. But in this case, the IFC I am using is a corporate one, which I cannot publish. Is there a way to send you the IFC without it being public?

Thank you very much.

### System Info 💻

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (20) x64 13th Gen Intel(R) Core(TM) i7-13700H
    Memory: 2.64 GB / 15.64 GB
  Binaries:
    Node: 20.11.1 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (126.0.2592.113)
    Internet Explorer: 11.0.22621.3527
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by agviegas** [comment]
File privately available [here](https://drive.google.com/file/d/1Y760r0ppN_1Sh4y3HrSXdeHh1LC-vsAl/view?usp=drive_link).

**Comment by usmanhussainESP** [comment]
Hello @agviegas,

To give you more context on this problem, I confirm that using the "web-ifc" version: "0.0.51" this same IFC was loaded correctly.
Because previously I was working with the openbim-components@1.4.14 version which internally uses the 0.0.51 version of the web-ifc.
The origin of the observed problem has been the migration of the components from 1.4.14 to 2.1.13.

Therefore, keeping this in mind, and from what I see the solution to the problem may take a considerable time, I am thinking of using version 0.0.51 in the latest versions of @thatopen/components. Is this possible?

I have tried to do the following:

```
this.fragmentIfcLoader = this.components.get(OBC.IfcLoader);
  this.fragmentIfcLoader.settings.autoSetWasm = false;
  this.fragmentIfcLoader.settings.wasm = {
      path: 'https://unpkg.com/web-ifc@0.0.51/',
      absolute : true,
  }
  this.fragmentIfcLoader.settings.webIfc.COORDINATE_TO_ORIGIN = true;
  await this.fragmentIfcLoader.setup();

```

But I get the error:

Missing field: "OPTIMIZE_PROFILES".

Can you give me any suggestions to bypass this problem temporarily?

Or is it not possible to use this old version of webfic with the new components?
Thank you very much.

**Comment by agviegas** [comment]
@usmanhussainESP can you try adding the field `OPTIMIZE_PROFILES: false` to `this.fragmentIfcLoader.settings.webIfc`?

**Comment by usmanhussainESP** [comment]
@agviegas I have tried what you suggested. But I got the following error:

TypeError: this.wasmModule.GetAllCrossSections is not a function.

When I start loading the model, I get a lot of GetMesh() type errors and finally the undefined function error.

![image](https://github.com/user-attachments/assets/17a8a866-d33e-448e-a13b-dde8010942a7)

It seems that the version I need is not supported.

Is there anything I can do to achieve this compatibility or is it worth waiting for the bug to be fixed?

Thank you.

**Comment by agviegas** [comment]
Hm, I see. Then I guess the only solution left is either to stick with the old version, or to stick to the latest and wait for the fix in the future 🙏🏻 sorry for this!

**Comment by maidi29** [comment]
Hi @agviegas, do you have a rough estimation on how long it will take to fix the issue with the missing faces? As already said, we see the issue in almost all of our models, and sometimes many faces are affected. I also tested one of the models with lots of issues in your link but no improvement:
<img width="1450" alt="image" src="https://github.com/user-attachments/assets/0a5d881b-27ba-430a-962e-6ec5edbe97ef">
How it should look like and also did with an old version:
<img width="575" alt="image" src="https://github.com/user-attachments/assets/02b5aa75-646a-4bce-aac0-e8ad716b5c94">

Rollback to version 1 of the engine_components is not really an option for us since we started the project with version 2

**Comment by agviegas** [comment]
@maidi29 right now we don't know. The person in charge of the geometry engine is out on vacations until the end of August. In addition, geometry problems are uncertain: some take hours, other takes weeks. 

If you are in a hurry and just want to use a previous version of web-ifc, my suggestion in the meantime is that you [fork the components repo](https://github.com/ThatOpen/engine_components), install the version of web-ifc you need and solve the errors that come up (there shouldn't be many). Happy to guide you in the process if you decide to go down this route!

**Comment by atheler** [comment]
Salut

I also stumbled across the artifacts and it seems the issues started with the update on the ray-triangle intersection https://github.com/QuimMoya/fuzzy-bools/commit/2cf2885065dcf5359dc42b9934cd7d0acb62f431. Here is a before and after comparison:
<img width="1792" alt="subtraction comparisson" src="https://github.com/user-attachments/assets/4ab08243-58c8-487e-ad98-67621c4eb84d">

@QuimMoya what were the goals of this update? Could the use of `GLM's glm::intersectRayTriangle` implementation be an alternative?

@agviegas who is in charge of the geometry engine?

It would be cool if we could solve this

Cheers

**Comment by agviegas** [comment]
@atheler right now it's @QuimMoya. Right now he's out in vacations, but feel free to shoot him a message for when he's back!

**Comment by QuimMoya** [comment]
@atheler 

Is it possible to obtain the IFC model you are using the last tests?

**Comment by atheler** [comment]
Hi @QuimMoya 

I did not use an IFC model but instead generated 3D data manually and stored it in text files:
- [wall.txt](https://github.com/user-attachments/files/16778071/wall.txt)
- [opening.txt](https://github.com/user-attachments/files/16778073/opening.txt)
- [result.txt](https://github.com/user-attachments/files/16778077/result.txt)

These are simple text files with the vertex data on the first and the triangle face indices on the second line.

Here is the C++ wrapper program for the subtracting the geometries (as a `.txt` file to make GitHub happy): [main.cpp.txt](https://github.com/user-attachments/files/16778101/main.cpp.txt).
I compiled against the version in your repo https://github.com/QuimMoya/fuzzy-bools and swapped some files.

```bash
clang++ main.cpp -std=c++17 -Ideps/glm -Ideps/cdt  # Compile
./a.out wall.txt opening.txt result.txt  # Usage
```

The geometries are rotated slightly by some degrees to trigger floating-point errors. Also found that changing `toleranceVectorEquality` can bring back some of the missing faces.

I can also share some Python code for the geometry generation and plotting if you would like to?

Best

**Comment by usmanhussainESP** [comment]
Hi @QuimMoya ,

Is there any news regarding this bug? Can we have an approximate forecast of when it might be fixed?
Thank you so much in advance.
Best regards.

**Comment by QuimMoya** [comment]
I have identified the root cause of the last issue. The whole process works fine, but it fails to correctly identify which triangles to retain and which to discard.

**Comment by QuimMoya** [comment]
![image](https://github.com/user-attachments/assets/005a4f67-b6a2-4a19-a1cc-0d5bb36fbb63)

Just changed that

![image](https://github.com/user-attachments/assets/c3b6224c-ecf8-4112-899c-826966641b7a)

**Comment by usmanhussainESP** [comment]
Hey @QuimMoya 

Thanks for the update. Will there be a new version with these changes that I can try with my IFC model? Have you tried with my IFC file and see if the problem has been solved?

Thank you very much.

**Comment by QuimMoya** [comment]
The last release should include many fixes. You can test with it

**Comment by dkumza** [comment]
> The last release should include many fixes. You can test with it

when its going to be released?

**Comment by QuimMoya** [comment]
Today

**Comment by dkumza** [comment]
new version didn't solved issues

**Comment by QuimMoya** [comment]
Can you share this model?

**Comment by QuimMoya** [comment]
Last week, we made several updates to the boolean engine, but I'm not sure if they resolve all of your issues. Please use the demo [thatopen.github.io/engine_web-ifc/demo](https://thatopen.github.io/engine_web-ifc/demo) to test your models again. Or you can share these models with us privately.

We were able to test the first model, and it seems to open correctly. We also tested the second case (the wall with holes), and that worked as well. Based on these results, I closed the issue.

The most recent improvements (some just a few days old) appear to address the majority of the problematic cases we've encountered over time, so we believe that many of the issues should now be resolved.

However, I don't have access to all your models. If you have any models that still exhibit significant bugs, please share them with us privately so we can investigate and identify the causes.

**Comment by QuimMoya** [comment]
**Important**

Please do not test the fuzzy bools library directly. It has been integrated into the web-ifc, so you won't see any improvements by testing fuzzy bools alone. Instead, you should use the demo in the link I sent to you in the previous message.

**Comment by d-kumza** [comment]
yes we will share our IFC files

**Comment by d-kumza** [comment]
> Last week, we made several updates to the boolean engine, but I'm not sure if they resolve all of your issues. Please use the demo [thatopen.github.io/engine_web-ifc/demo](https://thatopen.github.io/engine_web-ifc/demo) to test your models again. Or you can share these models with us privately.
> 
> We were able to test the first model, and it seems to open correctly. We also tested the second case (the wall with holes), and that worked as well. Based on these results, I closed the issue.
> 
> The most recent improvements (some just a few days old) appear to address the majority of the problematic cases we've encountered over time, so we believe that many of the issues should now be resolved.
> 
> However, I don't have access to all your models. If you have any models that still exhibit significant bugs, please share them with us privately so we can investigate and identify the causes.

strange on this github demo app, i see no issues. But on thatopen template i see... 
` "dependencies": {
    "@thatopen/components": "~2.2.12",
    "@thatopen/components-front": "~2.2.2",
    "@thatopen/fragments": "~2.2.0",
    "@thatopen/ui": "~2.2.2",
    "@thatopen/ui-obc": "~2.2.5",
    "jszip": "3.10.1",
    "three": "0.160.0",
    "web-ifc": "0.0.59"
  }`

**Comment by QuimMoya** [comment]
> strange on this github demo app, i see no issues. But on thatopen template i see...

The latest updates haven't been released yet. Once we release them, you will see improvements in thatopen as well.

**Comment by d-kumza** [comment]
> > strange on this github demo app, i see no issues. But on thatopen template i see...
> 
> The latest updates haven't been released yet. Once we release them, you will see improvements in thatopen as well.

Great, what approximate time till you release for that open?

**Comment by QuimMoya** [comment]
I think these question are more on the side of thatopen. I'm more focused on geometry :)

Anyway, if you agree I will close this issue.

**Comment by agviegas** [comment]
@d-kumza the reason the web-ifc demo is smooth is that it merges geometries together. This has 2 problems:
- Memory usage scales linearly with the size of the model, so that there's a hard limit on the size of the models you can open depending on your machine.
- Items can't be easily highlighted/isolated/colored/etc.

If you are facing performance issues, feel free to open an issue [here](https://github.com/ThatOpen/engine_components/issues). Before that, I suggest you check out the [culler tutorial](https://docs.thatopen.com/Tutorials/Components/Core/Cullers) and [streaming tutorial](https://docs.thatopen.com/Tutorials/Components/Front/IfcStreamer).
